disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
  - large_tuple
  - function_body_length
  - identifier_name
opt_in_rules:
  - empty_count
included:
  - Sources
excluded:
  - .build/checkouts
  - .build/repositories
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
line_length: 120
type_body_length:
  - 300
  - 400
file_length:
  warning: 500
  error: 1200
type_name:
  min_length: 4
  max_length:
    warning: 40
    error: 50
  excluded: iPhone
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
