language: objective-c
osx_image: xcode8.3
branches:
  only:
    - master
    - develop
    - /^issue.*$/
    - /\s*([\d.]+)/
matrix:
  include:
    - script:
      # workaround
      - ./install_swiftlint.sh swiftlint
      env: JOB=swiftlint
      before_install: brew update
    - script: ./install_swiftlint.sh test-server
      env: JOB=test-server
      before_install: ./install_swiftlint.sh pre-build
# before_install:
#     - brew update
# script:
#     - ./install_swiftlint.sh
