language: objective-c
branches:
  only:
    - master
    - develop
    - /^issue.*$/
    - /\s*([\d.]+)/
matrix:
  include:
    - script:
      # workaround
      - ./install_swiftlint.sh swiftlint
      osx_image: xcode8.3
      env: JOB=swiftlint
      before_install: brew update
    - script: ./install_swiftlint.sh test-server
      os: osx
      osx_image: xcode8.3
      env: JOB=test-server XCODE=8.3
      before_install: ./install_swiftlint.sh pre-build-mac
    # - script: ./install_swiftlint.sh test-server
    #   os: osx
    #   osx_image: xcode9
    #   env: JOB=test-server XCODE=9
    #   before_install: ./install_swiftlint.sh pre-build
    # - script: ./install_swiftlint.sh test-server
    #   os: linux
    #   env: JOB=test-server
    #   before_install: ./install_swiftlint.sh pre-build-linux
# before_install:
#     - brew update
# script:
#     - ./install_swiftlint.sh
