language: objective-c
branches:
  only:
    - master
    - develop
    - /^issue.*$/
    - /\s*([\d.]+)/
matrix:
  include:
    - script: ./install_swiftlint.sh tests-macos # tests
      os: osx
      osx_image: xcode9
      env: JOB=tests-macos
      before_script: ./install_swiftlint.sh before-tests-couch-db
      before_install:
        - brew install couchdb
        - ./install_swiftlint.sh before-tests-macos
        - ./install_swiftlint.sh before-tests-script
