language: objective-c
branches:
  only:
    - master
    - develop
    - /^issue.*$/
    - /\s*([\d.]+)/
before_install:
    - brew update
    - brew list swiftlint || brew install swiftlint
script:
  - swiftlint
