language: objective-c
branches:
  only:
    - master
    - develop
    - /^issue.*$/
    - /\s*([\d.]+)/
matrix:
  include:
    - script: # Swiftlint
      - ./install_swiftlint.sh swiftlint
      os: osx
      osx_image: xcode8.3
      env: JOB=swiftlint
      before_install:
        - brew update
        - ./install_swiftlint.sh before-swiftlint
    - script: ./install_swiftlint.sh tests-macos # tests
      os: osx
      osx_image: xcode8.3
      env: JOB=tests-macos
      before_script: ./install_swiftlint.sh before-tests-script
      before_install: brew install couchdb; ./install_swiftlint.sh before-tests-macos
    - script: ./install_swiftlint.sh jazzy #jazzy
      os: osx
      osx_image: xcode8.3
      env: JOB=Jazzy
      before_install: gem install jazzy; ./install_swiftlint.sh before-tests-macos
